# Generated by Django 5.2.15 on 2026-06-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=80, verbose_name='Название (RU)')),
                ('name_en', models.CharField(max_length=80, verbose_name='Название (EN)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Бутылочный напиток',
                'verbose_name_plural': 'Бутылочные напитки',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер')),
                ('name_ru', models.CharField(max_length=80, verbose_name='Название (RU)')),
                ('name_en', models.CharField(max_length=80, verbose_name='Название (EN)')),
                ('flavor', models.CharField(choices=[('Сладкий', 'Сладкий'), ('Кислый', 'Кислый'), ('Горький', 'Горький'), ('Острый', 'Острый'), ('Игристый', 'Игристый')], max_length=20, verbose_name='Вкус')),
                ('tag2', models.CharField(blank=True, max_length=30, verbose_name='Тег 2')),
                ('tag3', models.CharField(blank=True, max_length=30, verbose_name='Тег 3')),
                ('adelhyde', models.PositiveSmallIntegerField(default=0, verbose_name='Adelhyde')),
                ('bronson', models.PositiveSmallIntegerField(default=0, verbose_name='Bronson')),
                ('flanergide', models.PositiveSmallIntegerField(default=0, verbose_name='Flanergide')),
                ('delta', models.PositiveSmallIntegerField(default=0, verbose_name='Pwd Delta')),
                ('karmotrine', models.PositiveSmallIntegerField(default=0, verbose_name='Karmotrine')),
                ('opt_karmotrine', models.BooleanField(default=False, verbose_name='Karmotrine опционально')),
                ('based_on', models.CharField(blank=True, max_length=80, verbose_name='На основе (классика)')),
                ('recipe', models.TextField(help_text='По одному ингредиенту в строке.', verbose_name='Рецепт')),
                ('method', models.TextField(verbose_name='Способ приготовления')),
                ('note', models.TextField(blank=True, verbose_name='Заметка о вкусе')),
                ('dossier', models.TextField(blank=True, verbose_name='Досье / история')),
                ('bonus', models.BooleanField(default=False, help_text='Отметь, если напиток не из канона бара.', verbose_name='Внештатная стойка')),
            ],
            options={
                'verbose_name': 'Коктейль',
                'verbose_name_plural': 'Коктейли',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст новости')),
                ('active', models.BooleanField(default=True, verbose_name='Показывать в строке')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Новость (бегущая строка)',
                'verbose_name_plural': 'Новости (бегущая строка)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
